spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: false
      idle-timeout: 30000
      pool-name: hikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
  task:
    execution:
      threadNamePrefix: task-execution
      pool:
        coreSize: 30
    scheduling:
      threadNamePrefix: task-scheduling
      pool:
        size: 10
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
mybatis:
  typeAliasesPackage: group.zealot.king
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    cache-enabled: false