spring:
  datasource:
    url: jdbc:mysql://www.zealot.group:3306/king?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zealot
    password: zealot.group
  redis:
    host: www.zealot.group
    port: 6379
    password: zealot.group
wx:
  appid: wx9bc9c5bfec0c3fe6
  secret: e67187280bf1a59ed7eec00bbbae90fc
